AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Plantilla CloudFormation para desplegar
  una instancia EC2 y un bucket S3.

Resources:

  DevOpsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      IamInstanceProfile: LabInstanceProfile

  DevOpsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "devops-bucket-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

Outputs:

  InstanceId:
    Description: ID de la instancia EC2
    Value: !Ref DevOpsInstance

  BucketName:
    Description: Nombre del bucket S3
    Value: !Ref DevOpsBucket
